export function pageTsxTemplate(params: { pageId: string; title: string }) {
  const { pageId, title } = params

  return `import React from 'react'
	import { useStore } from 'zustand'
	import { z } from 'zod'

	import { createStoreBridgeBrowserSync } from 'bridge-store/browser'
	import { Button, Card, CardContent, CardHeader, CardTitle } from '@/ui'

type State = {
  updatedAt: number
  items: Array<{ id: string; text: string }>
  dispatch: (action: { type: string; payload?: any }) => void
}

	const stateSchema = z.object({
	  updatedAt: z.number().describe('unix ms timestamp'),
	  items: z.array(z.object({ id: z.string(), text: z.string() })),
	})

	const bridge = createStoreBridgeBrowserSync<State>({
	  bridgeUrl: (window as any).__STOREBRIDGE_WS__ ?? 'ws://127.0.0.1:8787',
	  pageId: ${JSON.stringify(pageId)},
	  storeKey: 'main',
  meta: {
    id: ${JSON.stringify(pageId)},
    title: ${JSON.stringify(title)},
    store: {
      stateSchema,
      actions: [
        {
          type: '${pageId}.setData',
          description: 'Agent writes new data to render',
          payloadSchema: z.object({
            updatedAt: z.number(),
            items: z.array(z.object({ id: z.string(), text: z.string() })),
          }),
        },
      ],
    },
  },
  createState: (set, get) => ({
    updatedAt: Date.now(),
    items: [],
    dispatch: (action) => {
      if (action.type === '${pageId}.setData') {
        const p = action.payload ?? {}
        set({ updatedAt: Number(p.updatedAt ?? Date.now()), items: p.items ?? [] })
      }
	    },
	  }),
	})

	const store = bridge.store

	export default function Page() {
	  const updatedAt = useStore(store as any, (s: any) => s.updatedAt)
	  const items = useStore(store as any, (s: any) => s.items)

	  React.useEffect(() => {
	    let closed = false
	    let close = () => {}

	    bridge
	      .attach()
	      .then((attached) => {
	        if (closed) {
	          attached.close()
	          return
	        }
	        close = attached.close
	      })
	      .catch((err) => {
	        console.error('[storebridge] attach failed', err)
	      })

	    return () => {
	      closed = true
	      close()
	    }
	  }, [])

	  return (
	    <div className="p-6">
	      <Card className="max-w-2xl">
        <CardHeader>
          <CardTitle>${title}</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="text-xs text-muted-foreground">updatedAt: {new Date(updatedAt).toLocaleString()}</div>

          <div className="space-y-2">
            {items.length === 0 ? (
              <div className="text-sm text-muted-foreground">No data yet. Use StoreBridge SDK to dispatch '${pageId}.setData'.</div>
            ) : (
              <ul className="list-disc pl-5 space-y-1">
                {items.map((it: any) => (
                  <li key={it.id} className="text-sm">{it.text}</li>
                ))}
              </ul>
            )}
          </div>

          <Button variant="secondary" onClick={() => store.getState().dispatch({ type: '${pageId}.setData', payload: { updatedAt: Date.now(), items: [{ id: crypto.randomUUID?.() ?? String(Math.random()), text: 'hello from browser' }] } })}>
            Write sample data (local)
          </Button>
        </CardContent>
      </Card>
    </div>
  )
}
`
}

export function metaJsonTemplate(params: { pageId: string; title: string }) {
  return JSON.stringify(
    {
      pageId: params.pageId,
      title: params.title,
      storeKey: 'main',
      description: 'Generated by storebridge-cli',
    },
    null,
    2,
  )
}
